.level=WARNING

# logging for ui
#org.g2fx.g2gui.level=INFO
#org.g2fx.g2gui.panel.ModulePane.level=INFO

# logging for backend/usb etc
#org.g2fx.g2lib.level=INFO
#org.g2fx.g2lib.state.UserModuleData.level=INFO
#org.g2fx.g2lib.state.ParamValues.level=INFO
#org.g2fx.g2lib.state.PatchVisuals.level=INFO
#org.g2fx.g2lib.state.PatchSettings.level=INFO

#org.g2fx.g2lib.usb.Usb.level=INFO
#org.g2fx.g2lib.usb.UsbSlotSender.level=INFO
#org.g2fx.g2lib.usb.OfflineSender.level=INFO

#org.g2fx.g2gui.bridge.PropertyBridge.level=INFO

#org.g2fx.g2gui.panel.AreaPane.level=INFO

#org.g2fx.g2lib.state.PatchModule.level=INFO

## Show BitBuffer and location details
#org.g2fx.g2lib.state.Patch.level=INFO
#org.g2fx.g2lib.protocol.Fields.level=INFO
#org.g2fx.g2lib.protocol.Sections.level=INFO

java.util.logging.SimpleFormatter.format=%1$tF %1$tT.%1$tL %4$s %3$s: %5$s%6$s%n

handlers=org.g2fx.g2lib.util.DualConsoleHandler
org.g2fx.g2lib.util.DualConsoleHandler.level=INFO
